resource_types:
- name: git-branches
  type: docker-image
  source:
    repository: vito/git-branches-resource
resources:
  - name: demo
    type: git-branches
    source:
      uri: https://github.com/diwakar-k/concourse_test
jobs:
  - name: createpipelines
    public: false
    plan:
      - get: demo
        trigger: true
      - task: createpipelines
        file: demo/create-pipeline.yml