resource_types:
- name: git-branches
  type: docker-image
  source:
    repository: vito/git-branches-resource
resources:
  - name: demo
    type: git-branches
    source:
      uri: https://github.com/diwakar-k/concourse_test.git
  - name: storage
    type: s3
    source:
    #   repository: 657757981076.dkr.ecr.us-east-1.amazonaws.com/test
      aws_access_key_id: {{aws-access-key}}
      aws_secret_access_key: {{aws-secret-key}}
      # Name of the bucket in S3 account
      bucket: rishi-demo
      region_name: ap-south-1  
jobs:
  - name: createpipelines
    public: false
    plan:
      - get: demo
        trigger: true
      - task: createpipelines
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: rguichard/fly
              tag: latest
          # This means a directory `source-repo/` will be mounted to the container in this task
          inputs:
            - name: demo
          # This ensures that the changes done as part of this task are retained in `source-repo/` for other tasks
          outputs:
            - name: source-repo
          run:
            path: /bin/sh
            args: ["./demo/create-pipeline.sh"]
              
      - put: storage
        inputs: 
          - source-repo
        

            