resource_types:
- name: git-branches
  type: docker-image
  source:
    repository: vito/git-branches-resource

resources:
  - name: demo
    type: git-branches
    source:
      uri: https://github.com/diwakar-k/concourse_test.git
jobs:
  - name: "pipeline"
    public: true
    plan:
      - get: demo
        trigger: true
      - task: createpipelines
        # privileged: true
        # file: demo/script/create-pipeline.yml
        config:
            platform: linux
            image_resource:
                type: registry-image
                source: { repository: rguichard/fly }
            inputs:
            - name: branches
              path: demo
            outputs:
            - name: output
            run:
                path: /bin/sh
                args: ["./demo/create-pipeline.sh"]
               